<?php

namespace DoctrineProxies\__CG__\App\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Programacao extends \App\Entities\Programacao implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entities\\Programacao' . "\0" . 'sequencia', '' . "\0" . 'App\\Entities\\Programacao' . "\0" . 'ordemProducao', '' . "\0" . 'App\\Entities\\Programacao' . "\0" . 'tempoTotal', '' . "\0" . 'App\\Entities\\Programacao' . "\0" . 'apontamentos', '' . "\0" . 'App\\Entities\\Programacao' . "\0" . 'roteiro', '' . "\0" . 'App\\Entities\\Programacao' . "\0" . 'recurso', '' . "\0" . 'App\\Entities\\Programacao' . "\0" . 'quantidadeProduzida'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entities\\Programacao' . "\0" . 'sequencia', '' . "\0" . 'App\\Entities\\Programacao' . "\0" . 'ordemProducao', '' . "\0" . 'App\\Entities\\Programacao' . "\0" . 'tempoTotal', '' . "\0" . 'App\\Entities\\Programacao' . "\0" . 'apontamentos', '' . "\0" . 'App\\Entities\\Programacao' . "\0" . 'roteiro', '' . "\0" . 'App\\Entities\\Programacao' . "\0" . 'recurso', '' . "\0" . 'App\\Entities\\Programacao' . "\0" . 'quantidadeProduzida'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Programacao $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getSequencia()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getSequencia();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSequencia', []);

        return parent::getSequencia();
    }

    /**
     * {@inheritDoc}
     */
    public function setSequencia($sequencia)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSequencia', [$sequencia]);

        return parent::setSequencia($sequencia);
    }

    /**
     * {@inheritDoc}
     */
    public function getApontamentos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApontamentos', []);

        return parent::getApontamentos();
    }

    /**
     * {@inheritDoc}
     */
    public function getOrdemProducao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrdemProducao', []);

        return parent::getOrdemProducao();
    }

    /**
     * {@inheritDoc}
     */
    public function setApontamentos($apontamentos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setApontamentos', [$apontamentos]);

        return parent::setApontamentos($apontamentos);
    }

    /**
     * {@inheritDoc}
     */
    public function setOrdemProducao($ordemProducao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrdemProducao', [$ordemProducao]);

        return parent::setOrdemProducao($ordemProducao);
    }

    /**
     * {@inheritDoc}
     */
    public function getTempoTotal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTempoTotal', []);

        return parent::getTempoTotal();
    }

    /**
     * {@inheritDoc}
     */
    public function getRoteiro()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoteiro', []);

        return parent::getRoteiro();
    }

    /**
     * {@inheritDoc}
     */
    public function getRecurso()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRecurso', []);

        return parent::getRecurso();
    }

    /**
     * {@inheritDoc}
     */
    public function setTempoTotal($tempoTotal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTempoTotal', [$tempoTotal]);

        return parent::setTempoTotal($tempoTotal);
    }

    /**
     * {@inheritDoc}
     */
    public function setRoteiro($roteiro)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRoteiro', [$roteiro]);

        return parent::setRoteiro($roteiro);
    }

    /**
     * {@inheritDoc}
     */
    public function setRecurso($recurso)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRecurso', [$recurso]);

        return parent::setRecurso($recurso);
    }

    /**
     * {@inheritDoc}
     */
    public function getQuantidadeProduzida()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQuantidadeProduzida', []);

        return parent::getQuantidadeProduzida();
    }

    /**
     * {@inheritDoc}
     */
    public function setQuantidadeProduzida($quantidadeProduzida)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQuantidadeProduzida', [$quantidadeProduzida]);

        return parent::setQuantidadeProduzida($quantidadeProduzida);
    }

    /**
     * {@inheritDoc}
     */
    public function adicionarApontamento(\App\Entities\Apontamento $apontamento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'adicionarApontamento', [$apontamento]);

        return parent::adicionarApontamento($apontamento);
    }

    /**
     * {@inheritDoc}
     */
    public function removerApontamento(\App\Entities\Programacao $programacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removerApontamento', [$programacao]);

        return parent::removerApontamento($programacao);
    }

    /**
     * {@inheritDoc}
     */
    public function jsonSerialize()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'jsonSerialize', []);

        return parent::jsonSerialize();
    }

}
